### ISSUE TITLE
Translate Testing and Profiler docs

### ISSUE THREAD

**Issue by carburo** [reactjs/es.reactjs.org#273]
The React core docs have been updated with a new Testing Section and a Profiler API article. We'd love to have translations available for these as soon as possible. If you would like to contribute to this effort leave a comment requesting one the articles. For any doubts about the process, you can check out the details in the general translation issue #4.

Here is the list of articles:
- [x] Profiler API @anodarse #280 
- [x] Testing Overview @rootlinux2 #275 
- [ ] Testing Recipes @carburo #302 
- [x] Testing Environments @gerson4g #277

**Comment by rootlinux2** [comment]
I'll be happy to help with Testing Overview translate.

**Comment by carburo** [comment]
@rootlinux2 You got it! :rocket:

**Comment by anodarse** [comment]
I will like to help with Profiler API translate

**Comment by carburo** [comment]
Ok @anodarse, you got it!

**Comment by rootlinux2** [comment]
I'm here again, this time I'll do Testing Recipes!

**Comment by Darking360** [comment]
Well sir @rootlinux2 you got it, go for it 💪

**Comment by Gerson4G** [comment]
I think this one can be updated (or even closed) @Darking360

**Comment by carburo** [comment]
Hi @anodarse! How is it going with the translation of the `Profiler API`. Are you still able to finish it? Please, let us know.

**Comment by carburo** [comment]
Hi @rootlinux2! Are you still working on `Testing Recipes`? Please, let us know if you are still able to finish it so that otherwise it can be assigned to someone else.

**Comment by rootlinux2** [comment]
Hi @carburo, Sorry by the delay, Some unplanned complications have delayed me, by next Friday I can have it ready!
