### ISSUE TITLE
Concurrent Mode Translation Progress

### ISSUE THREAD

**Issue by carburo** [reactjs/es.reactjs.org#316]
The React core docs have been updated with a new Concurrent Mode Section. We'd love to have a translation available as soon as possible. If you would like to contribute to this effort leave a comment claiming one the articles.

Some articles already have a Translation Draft. You could finish your translation based on that. The existing drafts may have missing markup, untranslated terms, inconsistent translations of a particular term among other issues that make them unsuitable for publishing in their current state. The disclaimer on top of each article has been left intentionally untranslated, as it is the same across all articles. You should use the one that finally gets approved in #312. 

For any doubts about the process, you can check out the details in the general translation issue #4 or leave a question on this thread.

Here is the list of articles:
- [x] [Introducing Concurrent Mode](https://github.com/reactjs/es.reactjs.org/blob/master/content/docs/concurrent-mode-intro.md) @carburo #312 
- [x] [Adopting Concurrent Mode](https://github.com/reactjs/es.reactjs.org/blob/master/content/docs/concurrent-mode-adoption.md) (Draft, #313) @Paynekk  #323 
- [ ] [Concurrent UI Patterns](https://github.com/reactjs/es.reactjs.org/blob/master/content/docs/concurrent-mode-patterns.md)  @carburo  #314 
- [x] [Suspense for Data Fetching](https://github.com/reactjs/es.reactjs.org/blob/master/content/docs/concurrent-mode-suspense.md) @carburo #315
- [x] [Concurrent Mode API Reference](https://github.com/reactjs/es.reactjs.org/blob/master/content/docs/concurrent-mode-reference.md) @cristianbgp #318

**Comment by cristianbgp** [comment]
I would love to work on `Concurrent Mode API Reference` 😅

**Comment by cristianbgp** [comment]
@carburo I've already upload a PR. I would like to get some feedback, this is my first time translating documentation 😄

**Comment by Paynekk** [comment]
I would like to work in `Adopting Concurrent Mode` :smiley:

**Comment by carburo** [comment]
Hi, @Paynekk, you got it then. Thank you!

**Comment by remediosaraya** [comment]
hola hay algo en lo que se pueda colaborar?

**Comment by carburo** [comment]
¡Hola @remediosaraya! Sí, todavía hay mucho por hacer. Puedes revisar los issues abiertos para la traducción de los artículos del blog y la sección de la comunidad (#201 #200). También puedes revisar las traducciones existentes para mejorarlas.
